# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course/%Y/%m', verbose_name='\u5c01\u9762\u56fe\u7247'),
        ),
    ]
