# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0004_teacher_image'),
        ('course', '0007_video_learn_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(default='', max_length=200, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.Teacher', verbose_name='\u8bfe\u7a0b\u6559\u5e08'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=200, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60'),
        ),
    ]
